name: Delete branch after PR merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete branch after merge
        if: github.event.pull_request.merged == true
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          git push origin --delete "$BRANCH_NAME"
